/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function encodeGif(input: string, output: string, options?: GifEncodeOptions | undefined | null, onProgress?: ((arg: ProgressEvent) => void) | undefined | null): Promise<GifEncodeResult>

export interface GifEncodeOptions {
  fps?: number
  width?: number
  height?: number
  quality?: number
  dither?: string
  temporalWindow?: number
  transparencyOptimization?: boolean
  verbose?: boolean
}

export interface GifEncodeResult {
  fileSizeBytes: number
  frameCount: number
  durationMs: number
  width: number
  height: number
}

export interface ProgressEvent {
  event: string
  stage?: string
  length?: number
  delta?: number
  message?: string
}
